### ISSUE TITLE
Error parsing Wahoo TickrX's .fit file

### ISSUE THREAD

**Issue by hnagib** [dtcooper/python-fitparse#113] opened 2020-09-06 22:22 UTC
I am running into an error when parsing any .fit files from my Wahoo TickrX. 

Here is the .fit file:
[2020-09-05-115751-FITNESS FB34-27-0.fit.zip](https://github.com/dtcooper/python-fitparse/files/5180368/2020-09-05-115751-FITNESS.FB34-27-0.fit.zip)

Here's the error I get when using version 1.1.0:

```python
~/opt/anaconda3/envs/wahoo/lib/python3.7/site-packages/fitparse/base.py in get_messages(self, name, with_definitions, as_dict)
    432         # If there are unparsed messages, yield those too
    433         while not self._complete:
--> 434             message = self._parse_message()
    435             if message and should_yield(message):
    436                 yield message.as_dict() if as_dict else message

~/opt/anaconda3/envs/wahoo/lib/python3.7/site-packages/fitparse/base.py in _parse_message(self)
    154                     add_dev_data_id(message)
    155                 elif message.mesg_type.name == 'field_description':
--> 156                     add_dev_field_description(message)
    157 
    158         self._messages.append(message)

~/opt/anaconda3/envs/wahoo/lib/python3.7/site-packages/fitparse/records.py in add_dev_field_description(message)
    451     base_type_id = message.get('fit_base_type_id').raw_value
    452     field_name = message.get('field_name').raw_value
--> 453     units = message.get('units').raw_value
    454 
    455     native_field_num = message.get('native_field_num')

AttributeError: 'NoneType' object has no attribute 'raw_value'
```

I was able to get around the issue by modifying line 291 of records.py in v1.0.0 from:
```python
    0x07: BaseType(name='string', identifier=0x07, fmt='s', parse=lambda x: x.split('\x00')[0] or None)
```
to:
```python
    0x07: BaseType(name='string', identifier=0x07, fmt='s', parse=lambda x: x)
```

Not sure if this is a bug or Wahoo's .fit files are just wack. Any help would be much appreciated!

**Comment by pR0Ps** [comment] 2020-09-07 03:10
Looks like a duplicate of #107

**Closed by pR0Ps** 2020-09-07 03:10 UTC
